version: "3"
services:
  nginx:
    build: server/nginx
    ports: ["80:80"]
    depends_on: [orthanc]
    restart: unless-stopped
    volumes: ["nginx:/etc/nginx:Z"]
  orthanc:
    build: server/orthanc
    restart: unless-stopped
    volumes: ["orthanc:/etc/orthanc:Z"]
  webapp:
    build: ./webapp
    restart: always
    depends_on:
      - orthanc
      - nginx
    ports:
      - "8080:8080"
    volumes:
      - ./webapp/src:/usr/webapp/src
      - ./webapp/public:/usr/webapp/public
    environment:
      PORT: 8080
      CHOKIDAR_USEPOLLING: 1
      CHOKIDAR_POLLINTERVAL: 3000
volumes:
  orthanc:
  nginx:
  webapp: