version: "3"
services:
  nginx:
    build: server/nginx
    ports: ["80:80"]
    depends_on: [orthanc]
    restart: unless-stopped
    volumes: ["nginx:/etc/nginx:Z"]
  orthanc:
    build: server/orthanc
    restart: unless-stopped
    volumes: ["orthanc:/etc/orthanc:Z"]
  angular:
    build: ./angular
    restart: always
    depends_on:
      - orthanc
      - nginx
    ports:
      - "4200:4200"
    volumes:
      - ./angular:/usr/angular
    environment:
      PORT: 4200
      CHOKIDAR_USEPOLLING: 1
      CHOKIDAR_POLLINTERVAL: 3000
volumes:
  orthanc:
  nginx:
  angular:
