version: "2"
services:
  nginx:
    build: nginx
    depends_on: [orthanc]
    restart: unless-stopped
    ports: ["80:80"]
    volumes: ["nginx:/etc/nginx:Z"]
  orthanc:
    build: orthanc
    restart: unless-stopped
    volumes: ["orthanc:/etc/orthanc:Z"]
volumes:
  orthanc:
  nginx:
